---
- name: Restart Service
  hosts: "{{ target_hosts }}"
  gather_facts: false
  tasks:
    - name: Restart service command
      shell: "echo 'restart web service' {{ service_name }}"
      become: true

