---
- name: Start Service
  hosts: "{{ target_hosts }}"
  gather_facts: false
  tasks:
    - name: Start service command
      shell: "echo 'start web service' {{ service_name }}"
      become: true

