---
- name: Restart Service
  hosts: "{{ target_hosts }}"
  gather_facts: false
  tasks:
    - name: Restart service command
      shell: "supervisorctl restart {{ service_name }}"
      become: true

